insert into maestros.estado_tecnologia (id, descripcion) values (1, 'Activo'), (2, 'Inactivo');

INSERT INTO contratacion.macroservicio (id, codigo, nombre) VALUES (1, '1', 'HOSPITALARIO'),(2, '2', 'QUIRURGICO'),(3, '3', 'CONSULTA EXTERNA'),(4, '4', 'SIN DETERMINAR'),(5, '5', 'URGENCIAS'),(6, '6', 'TRANSPORTE ESPECIAL DE PACIENTES'),(7, '7', 'APOYO DIAGNOSTICO Y COMPLEMENTACION TERAPEUTICA'),(8, '8', 'OTROS SERVICIOS'),(9, '9', 'PROMOCION Y PREVENCION'),(10, '10', 'PROCESOS'),(11, '0', 'EMPRESARIAL');

INSERT INTO contratacion.portafolio (id, fecha_insert) VALUES (1, now());
INSERT INTO contratacion.portafolio (id, fecha_insert) VALUES (2, now());
INSERT INTO contratacion.portafolio (id, fecha_insert) VALUES (3, now());

INSERT INTO maestros.procedimiento (id, codigo, descripcion, nivel_autorizacion, nivel_complejidad, estado_procedimiento_id, tipo_ppm_id, tipo_pago_requerido_enum, edad_ini, edad_fin, es_quirurgico, es_recobrable, es_internacion, fecha_insert, fecha_update, codigo_emssanar, tipo_procedimiento_id, es_excluyente) VALUES (1, '020602', 'OSTEOPLASTIA CRANEAL', 2, 3, 1, 1, 5, 360, 43200, 1, 0, 1, '2016-02-08 14:05:01.841297', '2020-01-16 16:21:11.059128', '01020602', 1, 0);
INSERT INTO maestros.procedimiento (id, codigo, descripcion, nivel_autorizacion, nivel_complejidad, estado_procedimiento_id, tipo_ppm_id, tipo_pago_requerido_enum, edad_ini, edad_fin, es_quirurgico, es_recobrable, es_internacion, fecha_insert, fecha_update, codigo_emssanar, tipo_procedimiento_id, es_excluyente) VALUES (2, '020700', 'EXTRACCION DE PLACA CRANEAL SOD', 2, 3, 2, 1, 5, 0, 43200, 1, 0, 1, '2014-04-24 18:04:03.620511', '2020-01-16 16:21:11.059128', '01020700', 1, 0);
INSERT INTO maestros.procedimiento (id, codigo, descripcion, nivel_autorizacion, nivel_complejidad, estado_procedimiento_id, tipo_ppm_id, tipo_pago_requerido_enum, edad_ini, edad_fin, es_quirurgico, es_recobrable, es_internacion, fecha_insert, fecha_update, codigo_emssanar, tipo_procedimiento_id, es_excluyente) VALUES (3, '020701', 'EXTRACCION O SUSTITUCION DE DISPOSITIVO DE FIJACION U OSTEOSINTESIS EN CRANEO', 2, 3, 1, 1, 5, 0, 43200, 1, 0, 1, '2019-01-06 21:32:06.005425', '2020-01-16 16:21:11.059128', '01020701', 1, 0);
INSERT INTO maestros.procedimiento (id, codigo, descripcion, nivel_autorizacion, nivel_complejidad, estado_procedimiento_id, tipo_ppm_id, tipo_pago_requerido_enum, edad_ini, edad_fin, es_quirurgico, es_recobrable, es_internacion, fecha_insert, fecha_update, codigo_emssanar, tipo_procedimiento_id, es_excluyente) VALUES (4, '021100', 'SUTURA SIMPLE DE DURAMADRE CEREBRAL SOD §', 2, 3, 2, 1, 5, 0, 43200, 1, 0, 1, '2015-02-26 10:01:50.773403', '2020-01-16 16:21:11.059128', '01021100', 1, 0);
INSERT INTO maestros.procedimiento (id, codigo, descripcion, nivel_autorizacion, nivel_complejidad, estado_procedimiento_id, tipo_ppm_id, tipo_pago_requerido_enum, edad_ini, edad_fin, es_quirurgico, es_recobrable, es_internacion, fecha_insert, fecha_update, codigo_emssanar, tipo_procedimiento_id, es_excluyente) VALUES (5, '021101', 'CORRECCION DE DESGARRO DURAL POST TRAUMATICO EN BOVEDA CRANEANA - POR CRANEOTOMIA', 2, 3, 1, 1, 5, 0, 43200, 1, 0, 1, '2014-04-24 18:04:03.620511', '2020-01-16 16:21:11.059128', '01021101', 1, 0);
INSERT INTO maestros.procedimiento (id, codigo, descripcion, nivel_autorizacion, nivel_complejidad, estado_procedimiento_id, tipo_ppm_id, tipo_pago_requerido_enum, edad_ini, edad_fin, es_quirurgico, es_recobrable, es_internacion, fecha_insert, fecha_update, codigo_emssanar, tipo_procedimiento_id, es_excluyente) VALUES (6, '021102', 'CORRECCION DE DESGARRO DURAL POST TRAUMATICO EN BOVEDA CRANEANA - CON PLASTIA DURAL', 2, 3, 1, 1, 5, 0, 43200, 1, 0, 1, '2014-04-24 18:04:03.620511', '2020-01-16 16:21:11.059128', '01021102', 1, 0);
INSERT INTO maestros.procedimiento (id, codigo, descripcion, nivel_autorizacion, nivel_complejidad, estado_procedimiento_id, tipo_ppm_id, tipo_pago_requerido_enum, edad_ini, edad_fin, es_quirurgico, es_recobrable, es_internacion, fecha_insert, fecha_update, codigo_emssanar, tipo_procedimiento_id, es_excluyente) VALUES (7, '021103', 'CORRECCION DE DESGARRO DURAL EN BASE DE CRANEO - POR CRANEOTOMIA', 2, 3, 1, 1, 5, 360, 43200, 1, 0, 1, '2014-04-24 18:04:03.620511', '2020-01-16 16:21:11.059128', '01021103', 1, 0);
INSERT INTO maestros.procedimiento (id, codigo, descripcion, nivel_autorizacion, nivel_complejidad, estado_procedimiento_id, tipo_ppm_id, tipo_pago_requerido_enum, edad_ini, edad_fin, es_quirurgico, es_recobrable, es_internacion, fecha_insert, fecha_update, codigo_emssanar, tipo_procedimiento_id, es_excluyente) VALUES (8, '021104', 'CORRECCION DE DESGARRO DURAL EN BASE DE CRANEO - CON PLASTIA AUTOLOGA O HETEROLOGA - POR CRANEOTOMIA', 2, 3, 1, 1, 5, 360, 43200, 1, 0, 1, '2014-04-24 18:04:03.620511', '2020-01-16 16:21:11.059128', '01021104', 1, 0);
INSERT INTO maestros.procedimiento (id, codigo, descripcion, nivel_autorizacion, nivel_complejidad, estado_procedimiento_id, tipo_ppm_id, tipo_pago_requerido_enum, edad_ini, edad_fin, es_quirurgico, es_recobrable, es_internacion, fecha_insert, fecha_update, codigo_emssanar, tipo_procedimiento_id, es_excluyente) VALUES (9, '021105', 'SUTURA SIMPLE DE DURAMADRE CEREBRAL', 2, 3, 1, 1, 5, 0, 43200, 1, 0, 1, '2016-02-08 14:05:01.841297', '2020-01-16 16:21:11.059128', '01021105', 1, 0);
INSERT INTO maestros.procedimiento (id, codigo, descripcion, nivel_autorizacion, nivel_complejidad, estado_procedimiento_id, tipo_ppm_id, tipo_pago_requerido_enum, edad_ini, edad_fin, es_quirurgico, es_recobrable, es_internacion, fecha_insert, fecha_update, codigo_emssanar, tipo_procedimiento_id, es_excluyente) VALUES (10, '021106', 'PLASTIA DURAL CON INJERTO', 2, 3, 1, 1, 5, 0, 43200, 1, 0, 1, '2019-01-06 21:32:06.005425', '2020-01-16 16:21:11.059128', '01021106', 1, 0);

INSERT INTO maestros.procedimiento_servicio (id, descripcion, cups, nivel_cups, reps_cups, complejidad, codigo_cliente, procedimiento_id) VALUES (1, 'OSTEOPLASTIA CRANEAL', '020602', '2', 206, 2, '01020602', 1);
INSERT INTO maestros.procedimiento_servicio (id, descripcion, cups, nivel_cups, reps_cups, complejidad, codigo_cliente, procedimiento_id) VALUES (2, 'EXTRACCION DE PLACA CRANEAL SOD', '020700', '3', 206, 2, '01020700', 2);
INSERT INTO maestros.procedimiento_servicio (id, descripcion, cups, nivel_cups, reps_cups, complejidad, codigo_cliente, procedimiento_id) VALUES (3, 'EXTRACCION O SUSTITUCION DE DISPOSITIVO DE FIJACION U OSTEOSINTESIS EN CRANEO', '020701', '2', 206, 2, '01020701', 3);
INSERT INTO maestros.procedimiento_servicio (id, descripcion, cups, nivel_cups, reps_cups, complejidad, codigo_cliente, procedimiento_id) VALUES (4, 'SUTURA SIMPLE DE DURAMADRE CEREBRAL SOD §', '021100', '3', 206, 1, '01021100', 4);
INSERT INTO maestros.procedimiento_servicio (id, descripcion, cups, nivel_cups, reps_cups, complejidad, codigo_cliente, procedimiento_id) VALUES (5, 'CORRECCION DE DESGARRO DURAL POST TRAUMATICO EN BOVEDA CRANEANA - POR CRANEOTOMIA', '021101', '3', 202, 3, '01021101', 5);
INSERT INTO maestros.procedimiento_servicio (id, descripcion, cups, nivel_cups, reps_cups, complejidad, codigo_cliente, procedimiento_id) VALUES (6, 'CORRECCION DE DESGARRO DURAL POST TRAUMATICO EN BOVEDA CRANEANA - POR CRANEOTOMIA', '021101', '2', 206, 2, '01021101', 5);
INSERT INTO maestros.procedimiento_servicio (id, descripcion, cups, nivel_cups, reps_cups, complejidad, codigo_cliente, procedimiento_id) VALUES (7, 'CORRECCION DE DESGARRO DURAL POST TRAUMATICO EN BOVEDA CRANEANA - CON PLASTIA DURAL', '021102', '3', 202, 3, '01021102', 6);
INSERT INTO maestros.procedimiento_servicio (id, descripcion, cups, nivel_cups, reps_cups, complejidad, codigo_cliente, procedimiento_id) VALUES (8, 'CORRECCION DE DESGARRO DURAL POST TRAUMATICO EN BOVEDA CRANEANA - CON PLASTIA DURAL', '021102', '2', 206, 2, '01021102', 6);
INSERT INTO maestros.procedimiento_servicio (id, descripcion, cups, nivel_cups, reps_cups, complejidad, codigo_cliente, procedimiento_id) VALUES (9, 'CORRECCION DE DESGARRO DURAL EN BASE DE CRANEO - POR CRANEOTOMIA', '021103', '3', 214, 3, '01021103', 7);
INSERT INTO maestros.procedimiento_servicio (id, descripcion, cups, nivel_cups, reps_cups, complejidad, codigo_cliente, procedimiento_id) VALUES (10, 'CORRECCION DE DESGARRO DURAL EN BASE DE CRANEO - POR CRANEOTOMIA', '021103', '2', 206, 2, '01021103', 7);
INSERT INTO maestros.procedimiento_servicio (id, descripcion, cups, nivel_cups, reps_cups, complejidad, codigo_cliente, procedimiento_id) VALUES (11, 'CORRECCION DE DESGARRO DURAL EN BASE DE CRANEO - CON PLASTIA AUTOLOGA O HETEROLOGA - POR CRANEOTOMIA', '021104', '3', 203, 3, '01021104', 8);
INSERT INTO maestros.procedimiento_servicio (id, descripcion, cups, nivel_cups, reps_cups, complejidad, codigo_cliente, procedimiento_id) VALUES (12, 'CORRECCION DE DESGARRO DURAL EN BASE DE CRANEO - CON PLASTIA AUTOLOGA O HETEROLOGA - POR CRANEOTOMIA', '021104', '2', 206, 2, '01021104', 8);
INSERT INTO maestros.procedimiento_servicio (id, descripcion, cups, nivel_cups, reps_cups, complejidad, codigo_cliente, procedimiento_id) VALUES (13, 'SUTURA SIMPLE DE DURAMADRE CEREBRAL', '021105', '2', 206, 2, '01021105', 9);
INSERT INTO maestros.procedimiento_servicio (id, descripcion, cups, nivel_cups, reps_cups, complejidad, codigo_cliente, procedimiento_id) VALUES (14, 'PLASTIA DURAL CON INJERTO', '021106', '2', 206, 2, '01021106', 10);

INSERT INTO contratacion.paquete_portafolio (id, portafolio_id, codigo, descripcion, valor, es_eliminar_tecnologias, es_modificar_cantidades, es_adicionar_tecnologias, es_modificar_valor, macroservicio_id, estado) VALUES (1, 1, '00Q7353S01', 'PAQUETE PARTO', 1, 1, 1, 1, 1, 2, 'Aprobado');
INSERT INTO contratacion.paquete_portafolio (id, portafolio_id, codigo, descripcion, valor, es_eliminar_tecnologias, es_modificar_cantidades, es_adicionar_tecnologias, es_modificar_valor, macroservicio_id, estado) VALUES (2, 2, '00Q0000426', 'PAQUETE BRONCOSCOPIA FIBROOPTICA CON LAVADO BRONQUIAL Y CON ANESTESIA', 100000, 1, null, 1, 1, 2, 'Aprobado');
INSERT INTO contratacion.paquete_portafolio (id, portafolio_id, codigo, descripcion, valor, es_eliminar_tecnologias, es_modificar_cantidades, es_adicionar_tecnologias, es_modificar_valor, macroservicio_id, estado) VALUES (3, 3, '00Q0000435', 'PAQUETE TRATAMIENTO PACIENTE CON GASTROSTOMIA', 100000, 1, null, null, 1, 1, 'Aprobado');

INSERT INTO contratacion.procedimiento_paquete (id, paquete_id, procedimiento_id, principal, etiqueta, cantidad, cantidad_minima, cantidad_maxima, costo_unitario, ingreso_cantidad, frecuencia_unidad) VALUES (1, 1, 1, 1, 'eps', 1, 1, 1, 100600, null, 'NA');
INSERT INTO contratacion.procedimiento_paquete (id, paquete_id, procedimiento_id, principal, etiqueta, cantidad, cantidad_minima, cantidad_maxima, costo_unitario, ingreso_cantidad, frecuencia_unidad) VALUES (2, 1, 2, 0, 'eps', 1, 1, 1, 100600, null, 'NA');
INSERT INTO contratacion.procedimiento_paquete (id, paquete_id, procedimiento_id, principal, etiqueta, cantidad, cantidad_minima, cantidad_maxima, costo_unitario, ingreso_cantidad, frecuencia_unidad) VALUES (3, 1, 3, 0, 'eps', 1, 1, 1, 100600, null, 'NA');

INSERT INTO contratacion.procedimiento_paquete (id, paquete_id, procedimiento_id, principal, etiqueta, cantidad, cantidad_minima, cantidad_maxima, costo_unitario, ingreso_cantidad, frecuencia_unidad) VALUES (4, 2, 3, 1, 'eps', 1, 1, 1, 100600, null, 'NA');
INSERT INTO contratacion.procedimiento_paquete (id, paquete_id, procedimiento_id, principal, etiqueta, cantidad, cantidad_minima, cantidad_maxima, costo_unitario, ingreso_cantidad, frecuencia_unidad) VALUES (5, 2, 4, 1, 'eps', 1, 1, 1, 100600, null, 'NA');
INSERT INTO contratacion.procedimiento_paquete (id, paquete_id, procedimiento_id, principal, etiqueta, cantidad, cantidad_minima, cantidad_maxima, costo_unitario, ingreso_cantidad, frecuencia_unidad) VALUES (6, 2, 5, 0, 'eps', 1, 1, 1, 100600, null, 'NA');

INSERT INTO contratacion.procedimiento_paquete (id, paquete_id, procedimiento_id, principal, etiqueta, cantidad, cantidad_minima, cantidad_maxima, costo_unitario, ingreso_cantidad, frecuencia_unidad) VALUES (7, 3, 5, 0, 'eps', 1, 1, 1, 100600, null, 'NA');
INSERT INTO contratacion.procedimiento_paquete (id, paquete_id, procedimiento_id, principal, etiqueta, cantidad, cantidad_minima, cantidad_maxima, costo_unitario, ingreso_cantidad, frecuencia_unidad) VALUES (8, 3, 7, 0, 'eps', 1, 1, 1, 100600, null, 'NA');
INSERT INTO contratacion.procedimiento_paquete (id, paquete_id, procedimiento_id, principal, etiqueta, cantidad, cantidad_minima, cantidad_maxima, costo_unitario, ingreso_cantidad, frecuencia_unidad) VALUES (9, 3, 9, 0, 'eps', 1, 1, 1, 100600, null, 'NA');