package com.conexia.contractual.utils.exceptions.constants;

/**
 * Created by pbastidas on 12/11/14.
 */
public enum PreContractualMensajeErrorEnum {
	NEGOCIACION_DIFERENTE_MODALIDAD,
	NEGOCIACION_CAPITA_DIFERENTE_REGIMEN,
	NEGOCIACION_NO_ENCONTRADA,
	SERVICIO_NO_ENCONTRADO_PORTAFOLIO,
	SERVICIO_NO_HABILITADO_NEGOCIACION,
	SERVICIO_YA_EXISTE_NEGOCIACION,
	PAQUETE_YA_EXISTE_NEGOCIACION,
	PROCEDIMIENTO_EXISTE_OTRO_SERVICIO,
	PROCEDIMIENTO_MAYOR_COMPLEJIDAD,
	PROCEDIMIENTO_YA_EXISTE_NEGOCIACION,
	PROCEDIMIENTO_DEROGADO,
	MEDICAMENTO_YA_EXISTE_NEGOCIACION,
	MEDICAMENTO_DEROGADO,
    SIN_VALOR_UPC,
    ERROR_NIVEL_DE_NEGOCIACION_BAJO,
    AREA_COBERTURA_SIN_SEDE_ERROR,
    TARIFARIO_NO_ENCONTRADO,
    ERROR_REPOSITORIO_ARCHIVOS,
    ARCHIVO_NO_ENCONTRADO,
    COMITE_ERR_FECHA_COMITE,
    COMITE_ERR_FECHA_LIMITE_PRES,
    COMITE_ERR_FECHA_LIMITE_PRES_VS_COMITE,
    COMITE_ERR_FECHA_COMITE_IGUAL_FECHA_LIM,
    COMITE_ERR_LIMITE_PRESTADORES,
    COMITE_ERR_FECHA_MENOR_IGUAL,
    COMITE_ERR_FECHA_MAYOR_OTRO_COMITE,
	ACTA_COMITE_FORM_ERROR,
	IMPRIMIR_ACTA_ESTADO_ILLEGAL,
    SYSTEM_ERROR,
    BUSINESS_ERROR,
    NIVEL_COMPLEJIDAD_NEGOCIACION,
    NIVEL_COMPLEJIDAD_PROCEDIMIENTO,
    ESTADO_PROCEDIMIENTO,
    PRESTADOR_NO_HABILITADO_PARA_SERVICIOS_FARMACEUTICOS,
    ESTADO_PROCEDIMIENTO_SERVICIO,
    NIVEL_PROCEDIMIENTO_NEGOCIACION,
    NEGOCIACION_SIN_FINALIZAR,
    TIPO_TECNOLOGIA_INVALIDO_MANUAL
    ;
}
