package com.conexia.contractual.definitions.transactional.contratourgencias;

import com.conexia.contratacion.commons.dto.contractual.legalizacion.LegalizacionContratoUrgenciasDto;

public interface ContratoUrgenciasVoBoTransaccionalRemote {

	public void asignarFirmaVoBoContratoUrgencias(LegalizacionContratoUrgenciasDto legalizacionContratoUrgenciasDto);
}
